import React, { createContext, useContext, useState } from "react";

export type Language = "vi" | "en" | "km";

interface LanguageContextProps {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  vi: {
    "nav.home": "Trang chủ",
    "nav.places": "Địa danh",
    "nav.chat": "Hỏi đáp AI",
    "nav.feedback": "Góp ý",
    "nav.announcements": "Bản tin",
    "nav.info": "Thông tin",
    "nav.profile": "Hồ sơ",
    "home.welcome": "Chào mừng đến với Núi Bà Đen",
    "home.subtitle": "Nóc nhà Nam Bộ - Điểm hẹn tâm linh & thiên nhiên kỳ vĩ",
    "home.quick_links": "Truy cập nhanh",
    "home.weather_warning": "Xem khuyến cáo thời tiết mới nhất",
    "home.visit_guide": "Hướng dẫn chi tiết tham quan di tích năm 2026",
    "places.title": "Khám Phá Địa Danh",
    "places.all": "Tất cả",
    "places.tam_linh": "Tâm Linh",
    "places.phong_canh": "Phong Cảnh",
    "places.dich_vu": "Cáp Treo & Dịch Vụ",
    "places.listen_guide": "Nghe thuyết minh di tích số",
    "places.stop_audio": "Dừng nghe",
    "places.detail": "Chi tiết",
    "chat.title": "Trợ Lý AI Núi Bà Đen",
    "chat.placeholder": "Hỏi tôi về giá vé, giờ mở cửa, trang phục, lịch sử...",
    "chat.send": "Gửi",
    "chat.suggested": "Câu hỏi thường gặp:",
    "feedback.title": "Phản Ánh & Góp Ý",
    "feedback.subtitle": "Ý kiến đóng góp giúp chúng tôi nâng cao chất lượng dịch vụ du lịch",
    "feedback.label.name": "Họ và tên của bạn",
    "feedback.label.phone": "Số điện thoại liên hệ",
    "feedback.label.type": "Loại góp ý phản ánh",
    "feedback.label.content": "Nội dung phản ánh chi tiết",
    "feedback.label.image": "Hình ảnh đính kèm (nếu có)",
    "feedback.submit": "Gửi góp ý của bạn",
    "feedback.success": "Gửi phản ánh thành công! Ban Quản lý sẽ sớm phản hồi.",
    "announcements.title": "Bản Tin & Cảnh Báo",
    "announcements.empty": "Không có thông báo mới nào",
    "info.title": "Hướng Dẫn Tham Quan",
    "info.ticket_title": "Bảng Giá Vé Cáp Treo Sun World",
    "info.opening_title": "Giờ Hoạt Động & Vận Hành",
    "info.rules_title": "Nội Quy Chiêm Bái & Lịch Sự",
    "info.history_title": "Lịch Sử & Sự Tích Linh Sơn Thánh Mẫu",
    "common.loading": "Đang tải dữ liệu...",
    "common.error": "Có lỗi xảy ra, vui lòng thử lại.",
    "common.no_data": "Không tìm thấy thông tin.",
    "profile.title": "Hành Trình Số Của Tôi",
    "profile.logged_out": "Chưa đăng nhập hệ thống du khách",
    "profile.login_btn": "Đăng nhập / Đăng ký",
    "profile.logout_btn": "Đăng xuất tài khoản",
    "profile.favorites": "Địa danh đã thả tim",
    "profile.no_favorites": "Bạn chưa lưu địa danh yêu thích nào.",
    "profile.stamps": "Hành Trình Dấu Ấn Di Sản",
    "profile.stamps_collected": "Đã tích lũy được {count}/3 dấu ấn",
    "profile.rewards": "Kỷ Niệm Hành Trình",
    "profile.no_rewards": "Hãy tham quan và thu thập đủ 3 dấu ấn di sản tại các địa danh linh thiêng để hoàn thành kỷ niệm hành trình của bạn!",
    "profile.copy": "Sao chép",
    "profile.copied": "Đã copy!",
    "realtime.weather": "Nhiệt độ đỉnh núi",
    "place.checkin.success": "Chúc mừng! Bạn đã check-in thành công di sản này.",
    "place.checkin.too_far": "Check-in thất bại! Bạn đang ở cách di tích khoảng {dist}m. Hãy di chuyển đến gần dưới 100m.",
    "place.checkin.btn": "Check-in GPS lấy Dấu ấn",
    "place.checkin.already": "Đã thu thập dấu ấn này",
    "profile.auth.login_tab": "ĐĂNG NHẬP",
    "profile.auth.signup_tab": "ĐĂNG KÝ KHÁCH",
    "profile.auth.fullname": "HỌ VÀ TÊN",
    "profile.auth.fullname_placeholder": "Nguyễn Văn A",
    "profile.auth.password": "MẬT KHẨU",
    "profile.auth.or": "HOẶC DÙNG THỬ",
    "profile.auth.demo_btn": "Đăng Nhập Nhanh (Demo)",
    "profile.guest_name": "Khách du lịch",
    "profile.edit.save": "Lưu",
    "profile.edit.cancel": "Hủy"
  },
  en: {
    "nav.home": "Home",
    "nav.places": "Places",
    "nav.chat": "AI Chat",
    "nav.feedback": "Feedback",
    "nav.announcements": "News",
    "nav.info": "Guide Info",
    "nav.profile": "Profile",
    "home.welcome": "Welcome to Black Lady Mountain",
    "home.subtitle": "The Roof of Southern Vietnam - Sacred Pilgrimage & Majestic Nature",
    "home.quick_links": "Quick Links",
    "home.weather_warning": "View latest weather advisory",
    "home.visit_guide": "Detailed visitor guide for 2026",
    "places.title": "Explore Attractions",
    "places.all": "All",
    "places.tam_linh": "Spiritual",
    "places.phong_canh": "Scenic",
    "places.dich_vu": "Cable & Services",
    "places.listen_guide": "Listen to digital guide",
    "places.stop_audio": "Stop audio",
    "places.detail": "Detail",
    "chat.title": "Black Lady Mountain AI Assistant",
    "chat.placeholder": "Ask about ticket prices, hours, dress code, history...",
    "chat.send": "Send",
    "chat.suggested": "Frequently Asked Questions:",
    "feedback.title": "Reports & Feedback",
    "feedback.subtitle": "Your feedback helps us improve our tourism quality",
    "feedback.label.name": "Your Full Name",
    "feedback.label.phone": "Contact Phone Number",
    "feedback.label.type": "Feedback Category",
    "feedback.label.content": "Detailed Description",
    "feedback.label.image": "Attach Photo (optional)",
    "feedback.submit": "Submit Feedback",
    "feedback.success": "Feedback sent successfully! The board will reply soon.",
    "announcements.title": "Announcements & Weather",
    "announcements.empty": "No new announcements available",
    "info.title": "Visitor Guide",
    "info.ticket_title": "Sun World Cable Car Ticket Prices",
    "info.opening_title": "Operating & Service Hours",
    "info.rules_title": "Worship Rules & Modesty Regulations",
    "info.history_title": "History & Legend of Linh Son Thanh Mau",
    "common.loading": "Loading data...",
    "common.error": "An error occurred, please try again.",
    "common.no_data": "No information found.",
    "profile.title": "My Digital Journey",
    "profile.logged_out": "Not signed in to visitor profile",
    "profile.login_btn": "Log In / Sign Up",
    "profile.logout_btn": "Log Out",
    "profile.favorites": "Saved Favorites",
    "profile.no_favorites": "No favorite places saved.",
    "profile.stamps": "Stamp Rally Journey",
    "profile.stamps_collected": "Collected {count}/3 heritage stamps",
    "profile.rewards": "Journey Memories",
    "profile.no_rewards": "Visit and collect all 3 heritage stamps at sacred landmarks to complete your digital journey memory!",
    "profile.copy": "Copy",
    "profile.copied": "Copied!",
    "realtime.weather": "Peak temperature",
    "place.checkin.success": "Congratulations! You have checked in at this heritage site.",
    "place.checkin.too_far": "Check-in failed! You are {dist}m away. Please move within 100m.",
    "place.checkin.btn": "Check-in via GPS",
    "place.checkin.already": "Stamp collected",
    "profile.auth.login_tab": "LOG IN",
    "profile.auth.signup_tab": "SIGN UP",
    "profile.auth.fullname": "FULL NAME",
    "profile.auth.fullname_placeholder": "John Doe",
    "profile.auth.password": "PASSWORD",
    "profile.auth.or": "OR TRY DEMO",
    "profile.auth.demo_btn": "Log In as Guest / Demo",
    "profile.guest_name": "Guest Tourist",
    "profile.edit.save": "Save",
    "profile.edit.cancel": "Cancel"
  },
  km: {
    "nav.home": "ទំព័រដើម",
    "nav.places": "ទីកន្លែង",
    "nav.chat": "ជជែកជាមួយ AI",
    "nav.feedback": "មតិយោបល់",
    "nav.announcements": "ព្រឹត្តិការណ៍",
    "nav.info": "ព័ត៌មានណែនាំ",
    "nav.profile": "ប្រវត្តិរូប",
    "home.welcome": "ស្វាគមន៍មកកាន់ភ្នំ Ba Den",
    "home.subtitle": "ដំបូលនៃភាគខាងត្បូងវៀតណាម - ចំណុចណាត់ជួបខាងជំនឿ និងធម្មជាតិដ៏អស្ចារ្យ",
    "home.quick_links": "តំណភ្ជាប់រហ័ស",
    "home.weather_warning": "មើលការណែនាំអំពីអាកាសធាតុចុងក្រោយបំផុត",
    "home.visit_guide": "ការណែនាំលម្អិតសម្រាប់ការទស្សនាក្នុងឆ្នាំ ២០២៦",
    "places.title": "ស្វែងរកទីកន្លែងទេសចរណ៍",
    "places.all": "ទាំងអស់",
    "places.tam_linh": "ជំនឿសាសនា",
    "places.phong_canh": "ទេសភាពធម្មជាតិ",
    "places.dich_vu": "កាប៊ីនឡាន និងសេវាកម្ម",
    "places.listen_guide": "ស្តាប់ការអធិប្បាយឌីជីថល",
    "places.stop_audio": "បញ្ឈប់សំឡេង",
    "places.detail": "លម្អិត",
    "chat.title": "ជំនួយការ AI ភ្នំ Ba Den",
    "chat.placeholder": "សួរខ្ញុំអំពីតម្លៃសំបុត្រ ម៉ោងបើកធ្វើការ សំលៀកបំពាក់ ប្រវត្តិសាស្ត្រ...",
    "chat.send": "ផ្ញើ",
    "chat.suggested": "សំណួរដែលសួរញឹកញាប់៖",
    "feedback.title": "ការរាយការណ៍ និងមតិយោបល់",
    "feedback.subtitle": "មតិយោបល់របស់អ្នកជួយយើងលើកកម្ពស់គុណភាពសេវាកម្មទេសចរណ៍",
    "feedback.label.name": "ឈ្មោះពេញរបស់អ្នក",
    "feedback.label.phone": "លេខទូរស័ព្ទទំនាក់ទំនង",
    "feedback.label.type": "ប្រភេទមតិយោបល់",
    "feedback.label.content": "ខ្លឹមសារលម្អិតនៃការរាយការណ៍",
    "feedback.label.image": "រូបភាពភ្ជាប់មកជាមួយ (បើមាន)",
    "feedback.submit": "ផ្ញើមតិយោបល់របស់អ្នក",
    "feedback.success": "ផ្ញើមតិយោបល់ជោគជ័យ! គណៈគ្រប់គ្រងនឹងឆ្លើយតបឆាប់ៗ។",
    "announcements.title": "ព្រឹត្តិការណ៍ និងការព្រមាន",
    "announcements.empty": "មិនមានសេចក្តីជូនដំណឹងថ្មីទេ",
    "info.title": "ការណែនាំអំពីការទស្សនា",
    "info.ticket_title": "តារាងតម្លៃសំបុត្រកាប៊ីនឡាន Sun World",
    "info.opening_title": "ម៉ោងប្រតិបត្តិការ និងការផ្តល់សេវាកម្ម",
    "info.rules_title": "បទប្បញ្ញត្តិក្នុងការសក្ការៈ និងការស្លៀកពាក់សមរម្យ",
    "info.history_title": "ប្រវត្តិ និងរឿងព្រេងរបស់ Linh Son Thanh Mau",
    "common.loading": "កំពុងទាញយកទិន្នន័យ...",
    "common.error": "មានកំហុសបានកើតឡើង សូមព្យាយាមម្តងទៀត។",
    "common.no_data": "រកមិនឃើញព័ត៌មានទេ។",
    "profile.title": "ដំណើរឌីជីថលរបស់ខ្ញុំ",
    "profile.logged_out": "មិនទាន់ចូលគណនីភ្ញៀវទេសចរទេ",
    "profile.login_btn": "ចូល / ចុះឈ្មោះ",
    "profile.logout_btn": "ចាកចេញពីគណនី",
    "profile.favorites": "ទីកន្លែងដែលបានរក្សាទុក",
    "profile.no_favorites": "មិនទាន់មានទីកន្លែងរក្សាទុកឡើយ។",
    "profile.stamps": "ដំណើរប្រមូលត្រាដានវិញ្ញាសា",
    "profile.stamps_collected": "ប្រមូលបាន {count}/3 ត្រា",
    "profile.rewards": "អនុស្សាវរីយ៍ធ្វើដំណើរ",
    "profile.no_rewards": "សូមទៅទស្សនា និងប្រមូលត្រាសញ្ញាបេតិកភណ្ឌទាំង ៣ នៅកន្លែងសក្ការៈបូជា ដើម្បីបង្ហើយការចងចាំដំណើរកម្សាន្តរបស់អ្នក!",
    "profile.copy": "ចម្លង",
    "profile.copied": "បានចម្លង!",
    "realtime.weather": "សីតុណ្ហភាពកំពូលភ្នំ",
    "place.checkin.success": "សូមអបអរសាទរ! អ្នកបាន check-in ដោយជោគជ័យនៅទីតាំងបេតិកភណ្ឌនេះ។",
    "place.checkin.too_far": "ការ check-in បរាជ័យ! អ្នកនៅឆ្ងាយ {dist}ម។ សូមចូលទៅជិតក្រោម ១០០ម។",
    "place.checkin.btn": "Check-in GPS យកត្រា",
    "place.checkin.already": "បានទទួលត្រានេះរួចហើយ",
    "profile.auth.login_tab": "ចូលគណនី",
    "profile.auth.signup_tab": "ចុះឈ្មោះភ្ញៀវ",
    "profile.auth.fullname": "ឈ្មោះពេញ",
    "profile.auth.fullname_placeholder": "សុខ សាន",
    "profile.auth.password": "លេខសម្ងាត់",
    "profile.auth.or": "ឬសាកល្បង",
    "profile.auth.demo_btn": "ចូលរហ័ស (Demo)",
    "profile.guest_name": "ភ្ញៀវទេសចរ",
    "profile.edit.save": "រក្សាទុក",
    "profile.edit.cancel": "បោះបង់"
  }
};

const LanguageContext = createContext<LanguageContextProps | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem("nui_ba_den_lang");
    return saved === "en" || saved === "vi" || saved === "km" ? saved : "vi";
  });

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem("nui_ba_den_lang", lang);
  };

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
};
